### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by bajtos** [marcelklehr/toposort#11]
Hello, could we bump up the version to 1.0.0 please?

Quoting from [semver](http://semver.org/#how-do-i-know-when-to-release-100):

> How do I know when to release 1.0.0?

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

There are already many users (dependents) counting on this module's API and functionality, and stability of that.

Also by moving beyond 0.x version range, it's easier for us users to decide what upgrade strategy we want to use (`^` to get all compatible updates, `~` to get bug fixes only).

@marcelklehr @jkroso

**Comment by marcelklehr** [comment]
I agree with you, this is a good move. I've just released v1.0.0 :sparkler:
