### ISSUE TITLE
Exclude graph.jpg from (NPM) package

### ISSUE THREAD

**Issue by vernondegoede** [marcelklehr/toposort#15]
Hi,

I just noticed the file `graph.jpg` on my computer, since it was downloaded through NPM (although I'm not sure which of the packages on my computer depend on it).

I think it would be better to create a separate build package to distribute on NPM. 

According to NPM, this package has been downloaded 1.153.649 times last month. The `graph.jpg` image is 10 KB. This means that only last month, 11.53649 gigabytes have been spent on downloading an image which is only using in the ReadMe :( 

Other libs have a build task for building the distributed package, I think this would be a nice one for this repo as well.

Cheers!

**Comment by marcelklehr** [comment]
This is the second time someone has approached me concerning the image size. I realize that 10kB is still pretty large, yet as someone else pointed out, reading docs offline can be tremendously helpful. So, would it be a compromise to switch to an svg to further reduce the size?

**Comment by vernondegoede** [comment]
Yeah you may be right. Using a SVG will probably already save a loooot of GB's :)
