### ISSUE TITLE
Is this tool able to detect circular dependencies?

### ISSUE THREAD

**Issue by PaulBernier** [marcelklehr/toposort#16]
Is this tool able to detect circular dependencies? And if so, what is the behaviour?

**Comment by marcelklehr** [comment]
Yes, it should be able to detect all kinds of circular dependencies and throw an error in that case. See the test cases, for example.

On March 17, 2017 10:22:50 PM GMT+01:00, Paul Bernier <notifications@github.com> wrote:
>Is this tool able to detect circular dependencies? And if so, what is
>the behaviour?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/marcelklehr/toposort/issues/16

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PaulBernier** [comment]
Great! Thanks.
